import Head from "next/head";
import Image from "next/image";
import Digits from "../components/Digits";
import Display from "../components/Display";
import Navbar from "../components/Navbar";
import SideDigit from "../components/SideDigit";
import UnderDisplay from "../components/UnderDisplay";

export default function Home() {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="App">
        <div className="calculator">
          <Navbar />
          <Display />
          <UnderDisplay />
          <Digits />
        </div>
      </div>
    </div>
  );
}
