import Head from "next/head";
import Image from "next/image";
import Display from "./components/Display";
import Navbar from "./components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="App">
        <div className="calculator">
          <Navbar />
          <Display />
        </div>
      </div>
    </div>
  );
}
